syntax = "proto3";


package auth;

service AuthService {
  rpc ValidateAccessToken (ValidateAccessTokenRequest) returns (ValidateAccessTokenResponse);
  rpc IssueServiceToken (IssueServiceTokenRequest) returns (IssueServiceTokenResponse);
}


service RoleService {
  rpc CheckRole (CheckRoleRequest) returns (CheckRoleResponse);
  rpc AddUserToRole (AddUserToRoleRequest) returns (AddUserToRoleResponse);
  rpc ListRoles (ListRolesRequest) returns (ListRolesResponse);
}

service TokenService {
  rpc InvalidateRefreshToken (InvalidateRefreshTokenRequest) returns (InvalidateRefreshTokenResponse);
}

message ValidateAccessTokenRequest {
  string token = 1;
}

message ValidateAccessTokenResponse {
  bool is_valid = 1;
  map<string, string> claims = 2;
}

message IssueServiceTokenRequest {
  string service_id = 1;
  bytes credentials = 2;
}

message IssueServiceTokenResponse {
  string token = 1;
}

message CheckRoleRequest {
  string subject_id = 1;
  string role = 2;
  map<string, string> context = 3;
}

message CheckRoleResponse {
  bool has_role = 1;
}

message AddUserToRoleRequest {
  string user_id = 1;
  string role_id = 2;
  string issuer_id = 3;
}

message AddUserToRoleResponse {
  bool success = 1;
}

message ListRolesRequest {
  string subject_id = 1;
}

message ListRolesResponse {
  repeated string roles = 1;
}

message InvalidateRefreshTokenRequest {
  string token_id = 1;
  string subject_id = 2;
}

message InvalidateRefreshTokenResponse {
  bool success = 1;
}
