package main

import exampleui "github.com/olegkapshai/auth-master/examples/internal/ui"

var storagePage = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>MinIO folder access demo</title><style id="examples-ui">` + exampleui.Styles + `</style></head><body>
<main class="page-shell" data-ui="page-shell"><header class="page-header"><p class="eyebrow">Folders, files, and inherited access</p><h1>MinIO storage workspace</h1><p class="page-description">Paste a fresh human access token, explore a seeded persona, and see folder-scoped permissions enforced through auth-master.</p></header>
<div class="card-stack">
<section class="card compact-card" data-ui="card" data-testid="registration-card"><h2>Create a storage account</h2><p class="card-help">Public demo registration creates its own one-time invite and provisions the private root folder. Production deployments must rate-limit and abuse-protect this endpoint.</p><div class="field-grid three"><label class="field">Login <input data-testid="register-login" autocomplete="username"></label><label class="field">Email <input data-testid="register-email" type="email" autocomplete="email"></label><label class="field">Password <input data-testid="register-password" type="password" autocomplete="new-password"></label></div><div class="actions"><button data-testid="register">Register</button></div><p class="result-label">Registration</p><output class="result" data-testid="register-result" aria-live="polite"></output></section>
<section class="card" data-ui="card" data-testid="workspace-card"><h2>Folder workspace</h2><p class="card-help">Seeded personas: <strong>storage-owner</strong> owns the tree; <strong>storage-reader</strong> downloads shared child files; <strong>storage-writer</strong> can upload there; <strong>storage-admin</strong> creates and shares child folders; <strong>storage-stranger</strong> is denied. Get a fresh token with <code>make -C examples token EXAMPLE=minio-storage PERSONA=owner</code>. Tokens expire; rerun that command and paste the replacement.</p>
<div class="storage-toolbar"><label class="field">Human access token <input class="token-field" data-testid="access-token" autocomplete="off"></label><label class="field">Folder owner UUID <input data-testid="owner-id"></label><div class="actions"><button data-testid="open-root">Open selected path</button></div></div>
<p class="result-label">Status</p><output class="result" data-testid="workspace-status" aria-live="polite"></output>
<nav aria-label="Folder breadcrumbs"><ol class="breadcrumb" data-testid="breadcrumbs"></ol></nav>
<div class="storage-layout"><section class="storage-panel"><h3>Folders</h3><ul class="entry-list" data-testid="folder-list"></ul><div class="subsection"><label class="field">New folder name <input data-testid="folder-name"></label><div class="actions"><button data-testid="create-folder">Create folder</button></div></div></section>
<section class="storage-panel"><h3>Files</h3><div class="field-grid"><label class="field span-all">Choose file <input data-testid="file-input" type="file"></label></div><div class="actions"><button data-testid="upload-file">Upload file</button></div><table class="file-table"><thead><tr><th>Name</th><th>Size</th><th>Action</th></tr></thead><tbody data-testid="file-list"></tbody></table></section>
<aside class="storage-panel"><h3>Selected-folder access</h3><p class="muted">Access on a folder inherits to its descendants, never to its parent or siblings.</p><div class="actions"><button class="secondary" data-testid="refresh-access">Refresh access</button></div><ul class="access-list" data-testid="access-list"></ul><div class="subsection"><label class="field">Share with group <input data-testid="share-group" placeholder="demo-readers"></label><div class="actions"><button data-testid="share-folder">Share selected folder</button></div></div></aside></div>
</section></div></main>
<script>
const q=id=>document.querySelector('[data-testid="'+id+'"]');
const initialParams=new URLSearchParams(location.search);
let initialPath=initialParams.get('path')||'';
let currentPath='';
q('owner-id').value=initialParams.get('owner')||'';
if(!initialPath)q('open-root').textContent='Open root';
const auth=()=>({Authorization:'Bearer '+q('access-token').value.trim()});
const encPath=p=>p.split('/').map(encodeURIComponent).join('/');
const folderBase=()=>'/folders/'+encodeURIComponent(q('owner-id').value.trim());
function status(message,error=false){q('workspace-status').textContent=message;q('workspace-status').dataset.state=error?'error':'ok'}
async function jsonCall(url,options={}){const response=await fetch(url,options);const text=await response.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={error:text}}if(!response.ok)throw new Error(data.error||('Request failed ('+response.status+')'));return {response,data}}
async function busy(button,work){button.disabled=true;try{await work()}catch(error){status(error.message,true)}finally{button.disabled=false}}
q('register').onclick=async()=>{const button=q('register');button.disabled=true;q('register-result').textContent='Creating account…';try{const {response,data}=await jsonCall('/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({login:q('register-login').value,email:q('register-email').value,password:q('register-password').value})});q('register-result').textContent=(response.status===201?'Ready':'Provisioning pending')+' — user '+data.user_id;q('owner-id').value=data.user_id;if(response.status===202){const retry=await jsonCall(data.retry,{method:'POST'});q('register-result').textContent='Ready — user '+retry.data.user_id}}catch(error){q('register-result').textContent='Registration failed — '+error.message}finally{button.disabled=false}};
function renderBreadcrumbs(){const list=q('breadcrumbs');list.replaceChildren();const parts=currentPath?currentPath.split('/'):[];[['Root',''],...parts.map((name,index)=>[name,parts.slice(0,index+1).join('/')])].forEach(([name,value])=>{const item=document.createElement('li');const button=document.createElement('button');button.className='secondary';button.textContent=name;button.onclick=()=>openFolder(value);item.append(button);list.append(item)})}
function renderEntries(entries){const folders=q('folder-list'),files=q('file-list');folders.replaceChildren();files.replaceChildren();for(const entry of entries){if(entry.kind==='folder'){const item=document.createElement('li'),button=document.createElement('button');button.className='entry-button';button.textContent='📁 '+entry.name;button.dataset.path=entry.path;button.onclick=()=>openFolder(entry.path);item.append(button);folders.append(item)}else{const row=document.createElement('tr'),name=document.createElement('td'),size=document.createElement('td'),action=document.createElement('td'),button=document.createElement('button');name.className='file-name';name.textContent=entry.name;size.textContent=entry.size+' bytes';button.className='secondary';button.textContent='Download';button.onclick=()=>download(entry.path,entry.name);action.className='file-actions';action.append(button);row.append(name,size,action);files.append(row)}}if(!folders.children.length){const item=document.createElement('li');item.className='empty-state';item.textContent='No child folders';folders.append(item)}if(!files.children.length){const row=document.createElement('tr'),cell=document.createElement('td');cell.colSpan=3;cell.className='empty-state';cell.textContent='No files in this folder';row.append(cell);files.append(row)}}
async function openFolder(folder){currentPath=folder;status('Loading '+(folder||'root')+'…');const {data}=await jsonCall(folderBase()+'?path='+encodeURIComponent(folder),{headers:auth()});const locationParams=new URLSearchParams();locationParams.set('owner',q('owner-id').value.trim());if(folder)locationParams.set('path',folder);history.replaceState(null,'','?'+locationParams);renderBreadcrumbs();renderEntries(data.entries);status('Opened '+(folder||'root'));await refreshAccess(false)}
q('open-root').onclick=()=>busy(q('open-root'),()=>{const target=initialPath;initialPath='';q('open-root').textContent='Open root';return openFolder(target)});
q('create-folder').onclick=()=>busy(q('create-folder'),async()=>{const {data}=await jsonCall(folderBase(),{method:'POST',headers:{...auth(),'Content-Type':'application/json'},body:JSON.stringify({parent:currentPath,name:q('folder-name').value})});q('folder-name').value='';status('Created folder '+data.path);await openFolder(currentPath)});
q('upload-file').onclick=()=>busy(q('upload-file'),async()=>{const file=q('file-input').files[0];if(!file)throw new Error('Choose a file first');const key=currentPath?currentPath+'/'+file.name:file.name;await jsonCall(folderBase()+'/objects/'+encPath(key),{method:'PUT',headers:{...auth(),'Content-Type':file.type||'application/octet-stream'},body:file});status('Uploaded '+file.name);await openFolder(currentPath)});
async function download(filePath,name){try{const response=await fetch(folderBase()+'/objects/'+encPath(filePath),{headers:auth()});if(!response.ok){const data=await response.json();throw new Error(data.error||'Download failed')}const blob=await response.blob(),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=name;link.click();URL.revokeObjectURL(link.href);status('Downloaded '+name)}catch(error){status(error.message,true)}}
async function refreshAccess(report=true){try{const {data}=await jsonCall(folderBase()+'/access?path='+encodeURIComponent(currentPath),{headers:auth()});const list=q('access-list');list.replaceChildren();for(const group of data.groups||[]){const item=document.createElement('li');item.className='access-pill';item.textContent=group;list.append(item)}if(!list.children.length){const item=document.createElement('li');item.className='muted';item.textContent='No direct group shares';list.append(item)}if(report)status('Access refreshed')}catch(error){q('access-list').replaceChildren();if(report)status(error.message,true)}}
q('refresh-access').onclick=()=>busy(q('refresh-access'),()=>refreshAccess(true));
q('share-folder').onclick=()=>busy(q('share-folder'),async()=>{await jsonCall(folderBase()+'/access/groups/'+encodeURIComponent(q('share-group').value),{method:'POST',headers:{...auth(),'Content-Type':'application/json'},body:JSON.stringify({path:currentPath})});status('Shared '+(currentPath||'root')+' with '+q('share-group').value);await refreshAccess(false)});
</script></body></html>`
